//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI31CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Graduate
    {
        public int id_student { get; set; }
        public int id_image { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public System.DateTime year_of_graduation { get; set; }
        public string BIO { get; set; }
        public string contact_data { get; set; }
        public string login { get; set; }
    
        public virtual UserOfSite UserOfSite { get; set; }
        public virtual Graduates_image Graduates_image { get; set; }
    }
}
