//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI31CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class LecturersImage
    {
        public byte[] id_image { get; set; }
        public int image_number { get; set; }
        public byte[] data { get; set; }
    }
}
