//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI31CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer
    {
        public int id_Lecturer { get; set; }
        public int id_image { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string subject { get; set; }
        public string BIO { get; set; }
        public string contact_data { get; set; }
    
        public virtual Lecturer_image Lecturer_image { get; set; }
    }
}
