//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI31CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer_image
    {
        public Lecturer_image()
        {
            this.Lecturers = new HashSet<Lecturer>();
        }
    
        public int id_image { get; set; }
        public byte[] data { get; set; }
    
        public virtual ICollection<Lecturer> Lecturers { get; set; }
    }
}
