//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMI31CourseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Course_ProjectEntities : DbContext
    {
        public Course_ProjectEntities()
            : base("name=Course_ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Administrator> Administrators { get; set; }
        public DbSet<Graduate> Graduates { get; set; }
        public DbSet<GraduatesImage> GraduatesImages { get; set; }
        public DbSet<Guest> Guests { get; set; }
        public DbSet<Lecturer> Lecturers { get; set; } 
        public DbSet<LecturersImage> LecturersImages { get; set; }
    }
}
